# Ejercicios 2

In [66]:
import numpy as np
import numpy.char as cha
import numpy.linalg as al

In [67]:
#Ejercicio 1
#Hay que generar un array del 0 al 99 y ver la diagonal principal y la superior a la principal.

array_lineal = np.linspace(start=0, stop=100, num=25, endpoint=False)
array_lineal = array_lineal.reshape(5,5)
print(array_lineal, "\n")
print(np.diag(array_lineal), "\n")#Obtenemos la diagonal principal
print(np.diag(array_lineal, k=1))#Gracias al parametro k obtenemos el la diagonal de arriba

[[ 0.  4.  8. 12. 16.]
 [20. 24. 28. 32. 36.]
 [40. 44. 48. 52. 56.]
 [60. 64. 68. 72. 76.]
 [80. 84. 88. 92. 96.]] 

[ 0. 24. 48. 72. 96.] 

[ 4. 28. 52. 76.]


In [68]:
#Ejercicio2: Hay que crear una matriz de 4 x 5 con el valor repetido 5. Unimos esta matriz a la del ejercicio anterior
#para conseguir dos nuevas matrices una de 5 x 9 y otra de 9 x 5

matriz_5 = np.full(shape=(4,5), fill_value=5)
print(matriz_5, "\n")
matriz_concatenada = np.concatenate((array_lineal,matriz_5), axis=0)
print(matriz_concatenada, "\n")
print(matriz_concatenada.T)




[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] 

[[ 0.  4.  8. 12. 16.]
 [20. 24. 28. 32. 36.]
 [40. 44. 48. 52. 56.]
 [60. 64. 68. 72. 76.]
 [80. 84. 88. 92. 96.]
 [ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.]] 

[[ 0. 20. 40. 60. 80.  5.  5.  5.  5.]
 [ 4. 24. 44. 64. 84.  5.  5.  5.  5.]
 [ 8. 28. 48. 68. 88.  5.  5.  5.  5.]
 [12. 32. 52. 72. 92.  5.  5.  5.  5.]
 [16. 36. 56. 76. 96.  5.  5.  5.  5.]]


In [69]:
#Ejercicio3: Tenemos un array inicial:
array_inicial = np.array(['    este es un curso de openwebinars     '],dtype=np.str_)
#Tenmos que convertirlo de tal manera que eliminemos los espacios, hagamos un array palabras y cada palabra empiece por mayúscula.
array_sin_espacios = cha.strip(array_inicial)
print(array_sin_espacios, "\n")#Eliminamos los espacios
array_por_palabras = cha.split(array_sin_espacios, sep=' ')
print(array_por_palabras, "\n")#Separamos por palabras el array
array_por_palabras = np.array(array_por_palabras[0]) #Esto convierte el array de tipo lista a un array de String dado que obtenemos una lista de lista,
#la posición 0 es el array entero, es decir de la lista la posición 0 es la lista/array con nuestras palabras.
array_capitalize = cha.capitalize(array_por_palabras)
print(array_capitalize, "\n")#Hacemos que cada letra inicial de cada palabra este en mayuscula
print(array_capitalize[cha.startswith(array_capitalize, prefix='E')])

['este es un curso de openwebinars'] 

[list(['este', 'es', 'un', 'curso', 'de', 'openwebinars'])] 

['Este' 'Es' 'Un' 'Curso' 'De' 'Openwebinars'] 

['Este' 'Es']


In [73]:
#Ejercicio 4: Tenemos dos matrices (ahora las hacemos) tenemos que operar con dichas matrices.
a = np.array([[3,1,2],[4,1,3],[2,0,1]])
b = np.array([[2,0,3],[1,1,1],[0,2,4]])
print(np.dot(a,b), "\n")
print(np.dot(b,a), "\n")
#La razon por la que no dan lo mismo es porque el orden de los factores si altera el resultado
#en las multiplicaciones matriciales, es decir no es conmutativo.
print(np.dot(a,2), "\n") #Multiplica la matriz por 2
#También vale esto: a * 2
print(np.vdot(a,b), "\n")
print(np.vdot(b,a))
 

[[ 7  5 18]
 [ 9  7 25]
 [ 4  2 10]] 

[[12  2  7]
 [ 9  2  6]
 [16  2 10]] 

[[6 2 4]
 [8 2 6]
 [4 0 2]] 

24 

24


array([[3, 1, 2],
       [4, 1, 3],
       [2, 0, 1]])

In [77]:
#Ejercicio 5: Con la matriz "a" que hemos definido antes vamos a operar:
print(al.matrix_power(a,3), "\n")#Elevamos al cubo la matiz con matrix_power
print(al.det(a), "\n")

y = np.array([3,2,5])
solucion_sistema_ecuacion = al.solve(a,y)
print(solucion_sistema_ecuacion)

[[ 89  21  57]
 [114  27  73]
 [ 42  10  27]] 

1.0 

[ 6. -1. -7.]
