# Ejercicios 3

In [ ]:
import numpy as np

SyntaxError: invalid syntax (1370842784.py, line 2)

In [24]:
#Ejercicio 1. A través de este array:
a = np.array([2,5,4,2,49,34,59,21,45,6,105])
#En primer lugar hay que imprimir si existe algun múltiplo de 7
print(np.any(a%7==0))
#Hay que devolver todos los valores del array que sean multiplos de 7 o sean menores de 40
b = a[np.logical_or(a%7==0, a < 40)]
print(b)

True
[  2   5   4   2  49  34  21   6 105]


In [25]:
#Ejercicio 2: Con el array que nos devuelve el ejercicio anterior:
#Hay que realizar los productos de los valores entre sí
print(np.prod(b), "\n")
#Hay que convertir el array en una matriz 3x3 y sumar sus filas
b = b.reshape(3,3)
print(b, "\n")
print(np.sum(b, axis=1), "\n")
#Hay que calcular el logaritmo en base 10 de todos los elementos que acabamos de crear
print(np.log10(b))

1763294400 

[[  2   5   4]
 [  2  49  34]
 [ 21   6 105]] 

[ 11  85 132] 

[[0.30103    0.69897    0.60205999]
 [0.30103    1.69019608 1.53147892]
 [1.32221929 0.77815125 2.0211893 ]]


In [29]:
#Ejercicio3: Con la matriz que tenemos y este vector:
v = np.array([0,3,5])
#Tenemos que sumarle a la matriz el vector
print(np.add(b,v), "\n")
print(np.divide(b,v), "\n")
#Para cambiar los valores infinitos hacemos:
h = np.where(np.isinf(np.divide(b,v)), 0, np.divide(b,v))
print(h, "\n")
print(np.max(h, axis=0), "\n")#Valor Máximo de las columnas
print(np.max(h, axis = 1), "\n")#Valor Máximo de las filas


[[  2   8   9]
 [  2  52  39]
 [ 21   9 110]] 

[[        inf  1.66666667  0.8       ]
 [        inf 16.33333333  6.8       ]
 [        inf  2.         21.        ]] 

[[ 0.          1.66666667  0.8       ]
 [ 0.         16.33333333  6.8       ]
 [ 0.          2.         21.        ]] 

[ 0.         16.33333333 21.        ] 

[ 1.66666667 16.33333333 21.        ] 



/var/folders/9q/x3cxwh3x3vz5xbqg35y1cbfh0000gn/T/ipykernel_15649/1278635187.py:5: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(b,v), "\n")
/var/folders/9q/x3cxwh3x3vz5xbqg35y1cbfh0000gn/T/ipykernel_15649/1278635187.py:7: RuntimeWarning: divide by zero encountered in divide
  h = np.where(np.isinf(np.divide(b,v)), 0, np.divide(b,v))


In [34]:
#Ejercicio 4:
#Con este array:
dataset = np.array([
    44, 28, 8, 34, 34, 26, 32, 12, 28, 6, 19, 12, 46, 20, 20, 49, 18,
    19, 15, 15, 43, 3, 7, 33, 27, 10, 18, 2, 3, 35, 35, 21, 17,
    36, 31, 16, 27, 6, 46, 29, 25, 26, 48, 1, 43, 10, 32,
    15, 32, 30, 40, 41, 11, 46, 3, 5, 40, 3, 14, 26, 25, 41,
    21, 30, 46, 1, 3, 4, 26, 9, 12, 39, 24, 34, 34, 38, 6, 23, 25, 41,
    15, 6, 3, 17, 13, 35, 48, 3, 24, 18, 32, 42,
    27, 32, 6, 16, 18, 10, 18, 34, 3, 46, 35, 30, 9,
    21, 29, 15, 49, 42, 10, 8, 27, 27, 29, 16, 12, 15, 31,
    21, 29, 15, 49, 42, 10, 8, 13, 14, 39, 30, 4, 48, 1, 19, 33,
    39, 9, 0, 24, 6, 12, 24, 29, 16, 11, 12, 13, 11
])
print(dataset, "\n")


[44 28  8 34 34 26 32 12 28  6 19 12 46 20 20 49 18 19 15 15 43  3  7 33
 27 10 18  2  3 35 35 21 17 36 31 16 27  6 46 29 25 26 48  1 43 10 32 15
 32 30 40 41 11 46  3  5 40  3 14 26 25 41 21 30 46  1  3  4 26  9 12 39
 24 34 34 38  6 23 25 41 15  6  3 17 13 35 48  3 24 18 32 42 27 32  6 16
 18 10 18 34  3 46 35 30  9 21 29 15 49 42 10  8 27 27 29 16 12 15 31 21
 29 15 49 42 10  8 13 14 39 30  4 48  1 19 33 39  9  0 24  6 12 24 29 16
 11 12 13 11]


In [36]:
#Hay que calcular la media y la mediana
media = np.mean(dataset)
print(media, "\n")
mediana = np.median(dataset)
print(mediana)
#Media != mediana porque distribución asimétrica, pero ligeramente.

22.66891891891892 

21.0


In [46]:
#Calculamos el tercer cuantil
tercerCuartil = np.quantile(dataset, q = 0.75)
print(np.max(dataset), "\n")
print(tercerCuartil, "\n")#Valor que deja el 75% de los datos atrás

#Calculamos el percentil 25
percentil25 = np.percentile(dataset, q = 25)
print(percentil25, "\n")#Valor que deja el 25% de los datos atrás
#Calculamos el percentil 50 que coincide con la mediana
percentil50 = np.percentile(dataset, q = 50)
print(percentil50)


49 

33.0 

11.75 

21.0


In [ ]:
#Calculamos la varianza y, a partir de ahí, hacemos la desviación típica
varianza = np.var(dataset)
print(varianza, "\n")
desviacion_tipica = np.sqrt(varianza)
#otra manera  = np.std(dataset)
print(desviacion_tipica)

184.78903396639882 

13.593713030897733


In [50]:
a = np.arange(10)
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])