# Funciones Estadísticas(importante)

In [2]:
import numpy as np

In [ ]:
#Funciones relacionadas con el ordén
a = np.array([2,3,4,5,6,7,8])
b = np.arange(0,20).reshape(4,5)
print(b,"\n")
print(np.min(a),"\n")#El míninmo de un array unidimensional
print(np.max(a),"\n")#El máximo de un array unidimensional

print(np.max(b, axis=0),"\n")#Imprime el máximo de la columnas(se lee de manera vertical)
print(np.max(b, axis=1),"\n")#Imprime el máximo de las filas(se lee de manera horizontal)
print(np.min(b, axis=0),"\n")#Imprime el mínimo de las columnas(se lee de manera vertical)
print(np.min(b, axis=1),"\n")#Imprime el mínimo de las filas(se lee de manera horizontal)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

2 

8 

[15 16 17 18 19] 

[ 4  9 14 19] 

[0 1 2 3 4] 

[ 0  5 10 15] 



In [ ]:
#Percentiles y cuantiles
f = np.arange(325,1500)
print(np.percentile(f, q=50))#Te dice el valor que deja un % atrás de la muestra. Esto es muy útil para reconocer outliers dado que
#si tenemos un dataset donde el valor máximo es de 2000 y el minimo de 100 y el percentil 90 es 350, te está diciendo que
#tenemos un 10% de los datos restantes entre el valor 350 y 2000 por lo que hay mucha diferencia y habrá que suavizar la distribución
print(np.quantile(f, 0.75))#Es otra manera de reconocer outliers que generarán sesgo en el desarrollo del modelo.Normalmente
#se usan los cuantiles 0.25, 0.5, 0.75 aunque vale cualquier número del 0 al 1.as_integer_ratio


912.0
1205.5


In [44]:
#Medias y Varianzas
print(np.mean(f))#La media no la usamos porque puede estar sesgada por los outliers
print(np.median(f))#Es el valor central donde deja, en términos de valor, el 50% de los datos a la izquierda y a la derecha.
h = np.array([123415,645,7765,890,456,8765])
print(np.median(h))
print(np.quantile(h, q=0.5))
print(np.percentile(h, q=50), "\n")
#La media es igual a la mediana en una distribución simétrica como en una campana de Gauss
#o en una distribución lineal perfectamente equilibrada como una progresión aritmética con una constante como diferencia común

y = np.array([[1,2,3,4,5],[6,7,8,9,10], [11,12,13,14,15]])
print(y)
print(np.mean(y, axis=0))#Media columnas
print(np.mean(y, axis=1),"\n")#Media filas

w = np.array([[2345,3,789],[23,67,3]])
print(w, "\n")
print(np.mean(w, axis=0), "\n")#Columnas
print(np.mean(w, axis=1), "\n")#Filas
print(np.median(w, axis=0), "\n")#Columnas
print(np.median(w, axis=1))#Filaas
#Con el array w, al no tener una distribución simétrica, la mediana y la media dan valores distintos


 

912.0
912.0
4327.5
4327.5
4327.5 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 6.  7.  8.  9. 10.]
[ 3.  8. 13.] 

[[2345    3  789]
 [  23   67    3]] 

[1184.   35.  396.] 

[1045.66666667   31.        ] 

[1184.   35.  396.] 

[789.  23.]


(2, 3)

In [47]:
#Desviación Estándar
hp = np.array([[23,667,54], [3306,8888,8844]])
print(hp, "\n")
print(np.std(hp, axis=0), "\n")#Desviación estándar de las columnas
print(np.std(hp, axis=1), "\n")#Desviación estándar de las filas

#La desviación estándar es la raíz cuadrada del promedio de las desviaciones al cuadrado de la media, es decir:
#std = sqtr/raíz cuadrada(mean(abs(x - x.mean())**2))

#La varianza sería:
print(np.var(hp, axis = 0), "\n")#Columnas
print(np.var(hp, axis = 1))#Filas
#Al final la varianza y la desviación estándar miden lo mismo pero la desviación estándar es más fácil de interpretar
#dado que está en las mismas unidades que los datos de los que disponemos. La desviacion estandar se calcula como 
#la raíz cuadrada de la varianza.

[[  23  667   54]
 [3306 8888 8844]] 

[1641.5 4110.5 4395. ] 

[ 296.54791631 2621.07068878] 

[ 2694522.25 16896210.25 19316025.  ] 

[  87940.66666667 6870011.55555556]
