# Manipulación de Arrays

In [1]:
import numpy as np

In [9]:
a = np.array([[1,2,3,4], [4,3,2,np.nan]])
a.shape
a.reshape((4,2))
a.ravel() # Con esto convertimos un array multidimensional(matriz) en un array unidimensional.
a.T # Con esto le da la vuelta a las dimensiones: en este caso teniamos un 4,2 pues sería un 2,4
#Estos serían los métodos más interesantes en cuanto a las dimensiones del array.

array([[ 1.,  4.],
       [ 2.,  3.],
       [ 3.,  2.],
       [ 4., nan]])

In [10]:
# Tipos de Arrays
np.asarray_chkfinite(a) # Método de numpy que nos indica si existen nan o infinitos dentro del array(si existiesen dará error)

ValueError: array must not contain infs or NaNs

In [25]:
# Unión de Arrays con np.concatenate
c = np.array([[1,2,4], [3,4,5]])
d = np.array([[2,34,7]])
print(c.shape)
print(d.shape, "\n")

print(np.concatenate((c, d), axis=0), "\n") #Es importante decir que axis es el parámetro que nos indica a nivel de que se concatena,
# si su valor es 0 entonces se concatena a nivel de fila y si su valor es 1 entonces será a nivel de columna

print(np.concatenate((c.T,d.T), axis = 1)) #Tenemos que aplicar el transpose para que tengan las mismas columnas y se pueda concatenar.

# También podemos usar np.stack y funciona igual.


(2, 3)
(1, 3) 

[[ 1  2  4]
 [ 3  4  5]
 [ 2 34  7]] 

[[ 1  3  2]
 [ 2  4 34]
 [ 4  5  7]]


In [ ]:
#Division de Arrays con np.split
f = np.arange(0,20)
f_impares = f[1:20:2]
print(f_impares, "\n")
np.split(f, indices_or_sections=4)
np.split(f, [2,10,14])# También se puede hacer por rangos de valores el split(es más interesante porque no hace falta poner 
# un nº de secciones que sean divisibles por la longitud del array para que devueva arrays del mismo tamaño)


[ 1  3  5  7  9 11 13 15 17 19] 



[array([0, 1]),
 array([2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19])]

In [90]:
#Añadir y eliminar elementos de un array

#Para insertar:
a = np.arange(0, 15, dtype='float32')
print(a)
np.insert(a, obj=3, values=[2.2, 2.5]) #Utilizamos insert para insertar en cualquier posición.
np.append(a, values=[5,6]) #Utilizamos append para insertar en la posición final.
np.delete(a, obj=4)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]


array([ 0.,  1.,  2.,  3.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14.], dtype=float32)

In [98]:
#Existen otros métodos como np.trim_zeros y np.unique.

bv = np.array([0,0,0,0,0,120,0,123,0,0,0,0,0])
np.trim_zeros(bv) #Elimina los ceros de antes y después de los valores que no son ceros. Si en medio de los valores hay un 0, se queda. 

#ui = np.asarray([1,1,1,1,1,23,45,7,9])
#np.unique(ui) 


array([120,   0, 123])