# Operaciones Matemáticas

In [1]:
import numpy as np

In [9]:
#Redondeo
a = 2.4926
print(np.round(a, 3),"\n")#El segundo parámetro nos indica a cuantos números decimales queremos redondear.
b = np.array([[1.234,2.789,3], [1.789, 8.546,4]])
print(np.round(b,2), "\n")#Podemos redondear también arrays enteros
print(np.ceil(b), "\n")#Va a redondear al siguiente entero
print(np.floor(b))#Va a redondear al entero anterior

2.493 

[[1.23 2.79 3.  ]
 [1.79 8.55 4.  ]] 

[[2. 3. 3.]
 [2. 9. 4.]] 

[[1. 2. 3.]
 [1. 8. 4.]]


In [17]:
c = np.array([2,3,4])
d = np.array([[1,2],[3,4],[5,6]])
print(np.prod(c),"\n") #Va a multiplicar todos los elementos de ese array en ordén
print(np.prod(d, axis=0),"\n")#Va a multiplicar en base a las filas(1*3*5, 2*4*6)
print(np.prod(d, axis=1),"\n")#Va a multiplicar en base a las columnas(1*2, 3*4, 5*6)
print(np.sum(c),"\n")#Va a sumar todos los elementos de ese array en ordén
print(np.sum(d, axis=0),"\n")#Va a sumar en base a las filas(1+3+5, 2+4+6)
print(np.sum(d, axis=1))#Va a sumar en base a las columnas(1+2, 3+4, 5+6) 

24 

[15 48] 

[ 2 12 30] 

9 

[ 9 12] 

[ 3  7 11]


In [ ]:
#Logaritmos y exponentes //El logaritmo no es mas que averiguar el número al que se eleva una base
#Es importante usar logaritmos en los análisis exploratorios de los datasets en pos de buscar una distribución normal que
#facilite el entrenamiento de un modelo de ML.
print(np.exp(c),"\n")#Esto nos da los resultados de elevar el número e a los valores de la matriz
p = np.power(np.e, c)#Da el mismo resultado que la operación de arriba
print(np.log(p), "\n")#Le aplicamos el logaritmo neperiano y volvemos a la matriz inicial dado que el logaritmo neperiano es en base e.
print(np.log10(c), "\n")#El logaritmo en base 10 de un número nos da como resultado el número al que elevamos 10 
#para que de como resultado dicho número 
print(np.log2(c), "\n")#El logaritmo en base 2 de un número nos da como resultado el número al que elevamos 2 
#para que de como resultado dicho número. Este es muy importante ya que nos da el número de bits que necesitamos para almacenar
#un dato.

[ 7.3890561  20.08553692 54.59815003] 

[2. 3. 4.] 

[0.30103    0.47712125 0.60205999] 

[1.        1.5849625 2.       ] 



In [28]:
#Operaciones aritméticas
#suma
v = np.array([[1,2,3], [4,5,6]])
g = np.array([5,6,7])
print(np.add(v,g), "\n")#El array v es multidimensional y lo que hacemos es sumarle a cada fila del array v el array g.
print(np.subtract(v,g), "\n")#Aqui lo que hacemos es restar
print(np.multiply(v,g), "\n")#Multiplicamos
print(np.divide(v,g))#Dividimos


[[ 6  8 10]
 [ 9 11 13]] 

[[-4 -4 -4]
 [-1 -1 -1]] 

[[ 5 12 21]
 [20 30 42]] 

[[0.2        0.33333333 0.42857143]
 [0.8        0.83333333 0.85714286]]
