# Rutinas para la creación de arrays

In [1]:
import numpy as np

In [7]:
# Con np.eye lo que hacemos es crear una matriz identidad de 3x3 cuya diagonal principal es 1
print(np.eye(4, k=1, dtype=int)) # k=1 indica que la diagonal principal se desplaza una posición hacia arriba y
# si fuera k=-1 se desplazaría una posición hacia abajo. Vale con cualquier número entero.

# Tamnbién tenemos la matriz identidad de 3x3 con np.identity
print(np.identity(3, dtype=int)) # Esta función solo tiene un parámetro que es el tamaño de la matriz identidad

# Existe np.full para la creación de matrices con un valor constante o si le pasamos un array con los valores será una fila
print(np.full(shape=(4,4) , fill_value=5)) # Creamos una matriz de 3x3 con todos los valores a 5
print(np.full(shape=(4,4), fill_value=[1,2,3,4])) # Creamos una matriz de 3x3 con los valores de la fila [1,2,3,4]

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [30]:
#Creación de Arrays desde datos existentes
np.fromstring('1 2 3 4 5 6 7 8 9 9', sep=' ') # Creamos un array a partir de una cadena de texto.
np.fromiter('abcde', dtype='U1')
np.fromiter([1,2,3,4,5], dtype=int) # Creamos un array a partir de un iterable con este si que podemos usar tanto caracteres como números.


array([1, 2, 3, 4, 5])

In [ ]:
# Creación de Arrays con np.loadtxt, crea un array en base a los datos de un fichero de texto(este es muy interesante)
array_desde_fichero = np.loadtxt('/Users/alejandro/Desktop/Proyectos_ML/Numpy/datos.txt', delimiter=' ') # Cargamos un array desde un fichero de texto
print(array_desde_fichero) # Mostramos el array cargado desde el fichero

[[ 1.  2.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [39]:
# Creación de rangos numéricos
a = np.linspace(start = 1, stop = 10, num = 5, endpoint=True, retstep=True)# El num dice el numero de elementos que quiere en el array.
# Con el parametro "endpoint" lo que hacemos es que incluimos o no el valor de stop en el array u retsep nos dice el salto que da el array
print(a)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), np.float64(2.25))


In [40]:
# Con np.tri lo que hacemos es crear una matriz de las dimensiones que le indiquemos y deja por encima de la diagonal 0s
# y por debajo de la diagonal 1s.
np.tri(5,5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])