# Álgebra Lineal con Numpy

In [17]:
import numpy as np
import numpy.linalg as al

In [14]:
# Lo primero que vamos a realizar es la multiplicación matricial

a = np.array([[3,2], [1, 3]], dtype='int32')
b = np.array([[2,2], [1,2]], dtype='int32')

np.dot(a,b)
np.dot(b,a)

array([[ 8, 10],
       [ 5,  8]], dtype=int32)

In [30]:
# El producto escalar de un vector es:
print(np.vdot(a,b))

# El producto interno se haria así:
c = np.arange(6).reshape(2,3)
d = np.arange(3)
print(np.inner(c,d), "\n")

#Para elevar una matriz debemos hacer:
e = np.array([[1,2,3,4],[3,5,5,7], [4,4,4,4], [345, 654, 76, 876]], dtype='int32', ndmin=2)
print(al.matrix_power(e,2), "\n")
print(np.dot(e,e))

17
[ 5 14] 

[[  1399   2640    329   3534]
 [  2453   4629    586   6199]
 [  1412   2660    352   3564]
 [304831 577168  71185 773638]] 

[[  1399   2640    329   3534]
 [  2453   4629    586   6199]
 [  1412   2660    352   3564]
 [304831 577168  71185 773638]]


In [32]:
#Valores propios / Determinantes y vectores propios
m = np.diag([4,3,2,1])
print(al.eig(m), "\n") #Asi se calculan los valores propios
print(al.det(m)) #Así se calcula el determinante de una matriz
 

EigResult(eigenvalues=array([4., 3., 2., 1.]), eigenvectors=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])) 

24.000000000000004


In [33]:
z = np.array([[3,1], [1,2]])
j = np.array([9,8])
# También se pueden resolver ecuaciones en numpy con np.linalg.solve()
al.solve(z,j) #Resuelve el sistema de ecuaciones basado en z(matriz coeficiente) y j(vector de términos independientes).
#Es decir multiplicar la matriz z por los valores x(a descubrir) nos da como resultado j.



array([2., 3.])