## Creación de Arrays/Matrices en Numpy

In [5]:
import numpy as np;
print(np.__version__)

2.2.2


In [29]:
#Vamos a generar arrays de diferentes formas.

array1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype='int')
array1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
array2 = np.array([[1,2,3,], [4,5,6,]], dtype='int', ndmin=2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# np.zeros sirve para crear un array de ceros de la dimensión que se le pase.
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
#np.ones sirve para crear un array de unos de la dimensión que se le pase.
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
#np.full sirve para crear un array de la dimensión que se le pase y con el valor que se le pase.
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [54]:
#np.arange sirve para crear un array de la dimensión que se le pase y con los valores de dicha dimension.
a = np.arange(0, 10, 1) # El último parametro sirve para darnos el salto que queremos dar.
a.reshape(2,5)# Con reshape podemos cambiar la forma del array y transformalo en una matriz con las dimensiones que queramos.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])